version: '3'
services:
    r:
        container_name: r-base
        build: .
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./workspace:/home/user/workspace
        tty: true